-- ==============================================================================
-- SCHEMA CƠ SỞ DỮ LIỆU SERVERLESS (POSTGRESQL TRÊN SUPABASE)
-- Nâng cấp: Quản lý tài khoản cán bộ, Báo cáo & Phân quyền xóa dữ liệu
-- ==============================================================================

-- 1. BẢNG QUẢN LÝ TÀI KHOẢN CÁN BỘ (officers)
CREATE TABLE IF NOT EXISTS public.officers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, -- Mã cán bộ (VD: CB01, CB02)
    name TEXT NOT NULL,         -- Họ và tên
    phone TEXT DEFAULT '',      -- Số điện thoại
    pin TEXT DEFAULT '123456',  -- Mã PIN đăng nhập của cán bộ
    status TEXT DEFAULT 'active', -- 'active' hoặc 'locked'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bật RLS cho bảng officers
ALTER TABLE public.officers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Mọi người đều có thể đọc danh sách cán bộ" ON public.officers FOR SELECT USING (true);
CREATE POLICY "Admin có thể thêm cán bộ" ON public.officers FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin có thể sửa cán bộ" ON public.officers FOR UPDATE USING (true);
CREATE POLICY "Admin có thể xóa cán bộ" ON public.officers FOR DELETE USING (true);

-- 2. BẢNG LƯU TRỮ BÁO CÁO CÔNG VIỆC (reports)
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    officer_name TEXT NOT NULL,
    customer_name TEXT DEFAULT '',
    address TEXT DEFAULT '',
    start_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_date DATE NOT NULL,
    end_time TIME NOT NULL,
    task_description TEXT NOT NULL,
    task_result TEXT NOT NULL,
    status TEXT DEFAULT 'Đạt yêu cầu', -- 'Đạt yêu cầu', 'Chờ bổ sung', 'Không đạt', 'Cần thẩm định lại'
    image_url TEXT DEFAULT '',
    latitude NUMERIC(10, 7) DEFAULT NULL,
    longitude NUMERIC(10, 7) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bật tính năng Row Level Security (RLS)
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Cho phép cán bộ thêm báo cáo" ON public.reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Cho phép đọc dữ liệu báo cáo" ON public.reports FOR SELECT USING (true);
CREATE POLICY "Cho phép cập nhật báo cáo" ON public.reports FOR UPDATE USING (true);
CREATE POLICY "Cho phép xóa báo cáo (từng mục hoặc hàng loạt)" ON public.reports FOR DELETE USING (true);

-- Tạo chỉ mục (Index) tăng tốc tìm kiếm và lọc dữ liệu
CREATE INDEX IF NOT EXISTS idx_reports_officer ON public.reports (officer_name);
CREATE INDEX IF NOT EXISTS idx_reports_start_date ON public.reports (start_date);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON public.reports (created_at DESC);

-- ==============================================================================
-- 3. BUCKET LƯU TRỮ HÌNH ẢNH TRÊN SUPABASE STORAGE
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('report-images', 'report-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

CREATE POLICY "Cho phép upload ảnh hiện trường" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'report-images');
CREATE POLICY "Cho phép xem ảnh công khai" ON storage.objects FOR SELECT USING (bucket_id = 'report-images');
CREATE POLICY "Cho phép xóa ảnh khi xóa báo cáo" ON storage.objects FOR DELETE USING (bucket_id = 'report-images');
