-- ==============================================================================
-- SCHEMA CƠ SỞ DỮ LIỆU SERVERLESS (POSTGRESQL TRÊN SUPABASE)
-- Hệ thống giám sát công việc thẩm định khách hàng
-- ==============================================================================

-- 1. TẠO BẢNG LƯU TRỮ BÁO CÁO CÔNG VIỆC (reports)
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    officer_name TEXT NOT NULL,
    customer_name TEXT DEFAULT '',
    address TEXT DEFAULT '',
    start_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_date DATE NOT NULL,
    end_time TIME NOT NULL,
    task_description TEXT NOT NULL,
    task_result TEXT NOT NULL,
    status TEXT DEFAULT 'Đạt yêu cầu', -- 'Đạt yêu cầu', 'Chờ bổ sung', 'Không đạt'
    image_url TEXT DEFAULT '',
    latitude NUMERIC(10, 7) DEFAULT NULL,
    longitude NUMERIC(10, 7) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Bật tính năng Row Level Security (RLS)
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Tạo chính sách cho phép mọi người gửi báo cáo (Insert)
CREATE POLICY "Cho phép cán bộ thêm báo cáo" 
ON public.reports 
FOR INSERT 
WITH CHECK (true);

-- Tạo chính sách cho phép đọc dữ liệu (Select)
CREATE POLICY "Cho phép đọc dữ liệu báo cáo" 
ON public.reports 
FOR SELECT 
USING (true);

-- Tạo chính sách cho phép Admin xóa hoặc cập nhật báo cáo
CREATE POLICY "Cho phép cập nhật báo cáo" 
ON public.reports 
FOR UPDATE 
USING (true);

CREATE POLICY "Cho phép xóa báo cáo" 
ON public.reports 
FOR DELETE 
USING (true);

-- Tạo chỉ mục (Index) tăng tốc tìm kiếm và lọc dữ liệu
CREATE INDEX IF NOT EXISTS idx_reports_officer ON public.reports (officer_name);
CREATE INDEX IF NOT EXISTS idx_reports_start_date ON public.reports (start_date);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON public.reports (created_at DESC);

-- ==============================================================================
-- 2. TẠO BUCKET LƯU TRỮ HÌNH ẢNH TRÊN SUPABASE STORAGE
-- ==============================================================================
-- Chạy các lệnh dưới đây để tạo bucket lưu ảnh công khai 'report-images'

INSERT INTO storage.buckets (id, name, public) 
VALUES ('report-images', 'report-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Cho phép upload ảnh vào bucket
CREATE POLICY "Cho phép upload ảnh hiện trường" 
ON storage.objects 
FOR INSERT 
WITH CHECK (bucket_id = 'report-images');

-- Cho phép xem và tải ảnh công khai
CREATE POLICY "Cho phép xem ảnh công khai" 
ON storage.objects 
FOR SELECT 
USING (bucket_id = 'report-images');
